<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FGOLocalPlatform</AssemblyName>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableDefaultItems>false</EnableDefaultItems>
    <Version>1.1.2</Version>
    <PublishReadyToRun>true</PublishReadyToRun>
    <TieredPGO>true</TieredPGO>
    <Product>FGOAC scooby</Product>
    <AssemblyTitle>FGOAC scooby</AssemblyTitle>
    <Company>FGOAC scooby</Company>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <Nullable>annotations</Nullable>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>platform.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace/>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="DeckReaderUI\**\*.cs"/>
    <Compile Include="DeckReaderUI.Kancolle\**\*.cs"/>
    <Compile Include="FGOLocalPlatform\**\*.cs"/>
    <Compile Include="FGOLocalPlatform.PhotoAssets\**\*.cs"/>
    <Compile Include="Properties\AssemblyInfo.cs"/>
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Include="app.xaml"/>
    <Page Include="audiosettingsview.xaml"/>
    <Page Include="cardquantitywindow.xaml"/>
    <Page Include="cardvariantswindow.xaml"/>
    <Page Include="controlsettingsview.xaml"/>
    <Page Include="cursorsettingsview.xaml"/>
    <Page Include="debugsettingsview.xaml"/>
    <Page Include="banners.xaml"/>
    <Page Include="diagnosticsview.xaml"/>
    <Page Include="mainwindow.xaml"/>
    <Page Include="nameprompt.xaml"/>
    <Page Include="newaccountdialog.xaml"/>
    <Page Include="photocontrols.xaml"/>
    <Page Include="serversettingsview.xaml"/>
    <Page Include="summonsettingswindow.xaml"/>
    <Page Include="whatsnewdialog.xaml"/>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="platform.ico"/>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="FGOLocalPlatform.CardNames.json" LogicalName="FGOLocalPlatform.CardNames.json"/>
    <EmbeddedResource Include="FGOLocalPlatform.CraftEffects.json" LogicalName="FGOLocalPlatform.CraftEffects.json"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8"/>
  </ItemGroup>
</Project>